/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraceEditorRouteImport } from './routes/grace-editor'
import { Route as IndexRouteImport } from './routes/index'

const GraceEditorRoute = GraceEditorRouteImport.update({
  id: '/grace-editor',
  path: '/grace-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grace-editor': typeof GraceEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grace-editor': typeof GraceEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grace-editor': typeof GraceEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grace-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grace-editor'
  id: '__root__' | '/' | '/grace-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraceEditorRoute: typeof GraceEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/grace-editor': {
      id: '/grace-editor'
      path: '/grace-editor'
      fullPath: '/grace-editor'
      preLoaderRoute: typeof GraceEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraceEditorRoute: GraceEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
